.TH EXITSTATUS "1" "Sep. 2013" "exitstatus 0" "User Commands"
.SH NAME
exitstatus \- exit for the value by a user
.SH SYNOPSIS
.B exitstatus <number>
.SH DESCRIPTION
Exit for the value by a user .

.SH "REPORTING BUGS"
Report bugs to: bkbin005@rinku.zaq.ne.jp

.SH COPYRIGHT
bkbin005@rinku.zaq.ne.jp .
.br
License SUSE-Public-Domain and GPL-3.0+ and LGPL-3.0+ .
.br
You are free to change and redistribute it.
