.TH KILLME "1" "Sep. 2013" "killme 0" "User Commands"
.SH NAME
killme \- kill own process .
.SH SYNOPSIS
.B killme [ -signal | -s signal]
.SH DESCRIPTION
Kill own process .

.SH SEE ALSO
kill(1)

.SH "REPORTING BUGS"
Report bugs to: bkbin005@rinku.zaq.ne.jp

.SH COPYRIGHT
bkbin005@rinku.zaq.ne.jp .
.br
License SUSE-Public-Domain and GPL-3.0+ and LGPL-3.0+ .
.br
You are free to change and redistribute it.
